name: 'Drupal Playground Admin'
type: 'Site'
description: 'Sets up shared admin modules and configuration.'
install:
  - coffee
  - dashboard
  - help
  - navigation
  - navigation_extra_tools
  - type_tray
  - queue_ui
config:
  strict: false
  import:
    navigation:
      - system.menu.content
      - system.menu.navigation-user-links
