prompt_logging: false
prompt_logging_tags: ''
default_providers:
  chat:
    provider_id: openai
    model_id: gpt-5-nano
  chat_with_complex_json:
    provider_id: openai
    model_id: gpt-5-nano
  chat_with_image_vision:
    provider_id: openai
    model_id: gpt-5-nano
  chat_with_structured_response:
    provider_id: openai
    model_id: gpt-5-nano
  chat_with_tools:
    provider_id: openai
    model_id: gpt-5-nano
  embeddings:
    provider_id: openai
    model_id: text-embedding-3-large
  moderation:
    provider_id: openai
    model_id: omni-moderation-latest
  speech_to_text:
    provider_id: openai
    model_id: whisper-1
default_vdb_provider: ''
