<?php

/**
 * @file
 * Legacy hooks for Term Reference module.
 */

use Drupal\Core\Field\FieldConfigInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\term_reference\Hook\TermReferenceHooks;

/**
 * Implements hook_field_config_insert().
 */
#[LegacyHook]
function term_reference_field_config_insert(FieldConfigInterface $field_config): void {
  \Drupal::service(TermReferenceHooks::class)->fieldConfigClearCache($field_config);
}

/**
 * Implements hook_field_config_update().
 */
#[LegacyHook]
function term_reference_field_config_update(FieldConfigInterface $field_config): void {
  \Drupal::service(TermReferenceHooks::class)->fieldConfigClearCache($field_config);
}

/**
 * Implements hook_field_config_delete().
 */
#[LegacyHook]
function term_reference_field_config_delete(FieldConfigInterface $field_config): void {
  \Drupal::service(TermReferenceHooks::class)->fieldConfigClearCache($field_config);
}
