#!/bin/bash

## Description: Runs all code fix utilities (phpcbf, eslint, stylelint)
## Usage: code-fix [args]
## Example: ddev code-fix\nddev code-fix web/modules/sandbox/entity_labels

echo "Running phpcbf..."
ddev phpcbf $@

echo "Running eslint --fix..."
ddev eslint --fix $@

echo "Running stylelint --fix..."
ddev stylelint --fix $@
