#!/bin/bash

## Description: Runs all code review utilities (phpcs, phpstan, eslint, stylelint)
## Usage: code-review [args]
## Example: ddev code-review\nddev code-review web/modules/sandbox/entity_labels

echo "Running phpcs..."
ddev phpcs $@

echo "Running phpstan..."
ddev phpstan $@

echo "Running cspell..."
ddev cspell $@

echo "Running eslint..."
ddev eslint $@

echo "Running stylelint..."
ddev stylelint $@
