name: 'Clinical Trials Recipe Milvus'
description: 'Sets up AI Search and Milvus for Clinical Trials discovery.'
type: 'Site'
recipes:
  - clinical_trials_gov_recipe_setup
install:
  - ai_agents
  - ai_assistant_api
  - ai_search
  - ai_vdb_provider_milvus
  - search_api
  - shortcut
config:
  strict: false
  import:
    ai_agents: '*'
    ai_assistant_api: '*'
    ai_vdb_provider_milvus:
      - ai_vdb_provider_milvus.settings
    search_api:
      - search_api.server.trials_milvus
      - search_api.index.trials_milvus
    shortcut: '*'
    ai_search:
      - ai_search.index.trials_milvus
  actions:
    ai.settings:
      simpleConfigUpdate:
        default_vdb_provider: milvus
