ai_schemadotorg_jsonld.settings:
  type: config_object
  label: 'AI Schema.org JSON-LD settings'
  mapping:
    entity_types:
      type: sequence
      label: 'Entity types'
      sequence:
        type: mapping
        label: 'Entity type'
        mapping:
          prompt:
            type: text
            label: 'Prompt'
          default_jsonld:
            type: text
            label: 'Default JSON-LD'
    breadcrumb_jsonld:
      type: boolean
      label: 'Include breadcrumb JSON-LD'
