name: 'Clinical Trials Recipe Milvus Chat'
description: 'Adds the Olivero DeepChat UI for the Clinical Trials Milvus experience.'
type: 'Site'
recipes:
  - clinical_trials_gov_recipe_milvus
install:
  - ai_chatbot
config:
  strict: false
  import:
    block:
      - block.block.olivero_trials_milvus_chat
  actions:
    user.role.anonymous:
      grantPermission: 'access deepchat api'
