name: 'ClinicalTrials.gov Data Elastic Recipe'
description: 'Sets up Search API, autocomplete, and Elasticsearch Connector for ClinicalTrials.gov data search.'
type: 'Site'
recipes:
  - clinical_trials_gov_recipe_data_setup
install:
  - better_exposed_filters
  - clinical_trials_gov_data
  - facets
  - facets_exposed_filters
  - search_api_autocomplete
  - search_api
  - search_api_spellcheck
  - shortcut
  - views_filters_summary
  - views_filters_summary_search_api
  - views_ajax_history
  - elasticsearch_connector
config:
  strict: false
  import:
    asset_injector:
      - asset_injector.css.trials_elasticsearch_olivero
      - asset_injector.js.trials_elasticsearch_olivero
    shortcut: '*'
    search_api:
      - search_api.server.trials_elasticsearch
      - search_api.index.trials_elasticsearch
    views:
      - views.view.trials_elasticsearch
