name: 'ClinicalTrials.gov Data Elastic Recipe'
description: 'Sets up Search API, autocomplete, and Elasticsearch Connector for ClinicalTrials.gov data search.'
type: 'Site'
install:
  - better_exposed_filters
  - clinical_trials_gov_data
  - facets
  - facets_exposed_filters
  - search_api_autocomplete
  - search_api
  - search_api_spellcheck
  - views_filters_summary
  - views_filters_summary_search_api
  - views_ajax_history
  - elasticsearch_connector
config:
  strict: false
  import:
    search_api:
      - search_api.server.trials_elasticsearch
      - search_api.index.trials_elasticsearch
    views:
      - views.view.trials_elasticsearch
    search_api_autocomplete:
      - search_api_autocomplete.search.trials_elasticsearch
  actions:
    user.role.anonymous:
      grantPermission: 'use search_api_autocomplete for trials_elasticsearch'
    user.role.authenticated:
      grantPermission: 'use search_api_autocomplete for trials_elasticsearch'
