name: 'Drupal Playground AI CKEditor'
description: >
  Adds AI-powered CKEditor integration to the Drupal Playground AI recipe.
type: 'Site'
recipes:
  - drupal_playground_ai

install:
  - ai_ckeditor
config:
  strict: false
  actions:
    editor.editor.basic_html:
      addItemToToolbar:
        item_name: aickeditor
        position: 0
      setProperties:
        settings.plugins.ai_ckeditor_ai:
          dialog:
            autoresize: 'min-width: 600px'
            height: '750'
            width: '900'
            dialog_class: ai-ckeditor-modal
          plugins:
            ai_ckeditor_completion:
              enabled: true
              provider: ''
            ai_ckeditor_help:
              enabled: false
            ai_ckeditor_modify_prompt:
              enabled: false
              provider: ''
            ai_ckeditor_reformat_html:
              enabled: true
              provider: ''
            ai_ckeditor_spellfix:
              enabled: false
              provider: ''
            ai_ckeditor_summarize:
              enabled: true
              provider: ''
            ai_ckeditor_tone:
              enabled: false
              provider: ''
              autocreate: false
              tone_vocabulary: tags
              use_description: false
            ai_ckeditor_translate:
              enabled: false
              provider: ''
              language_source: lang
              autocreate: false
              translate_vocabulary: tags
              use_description: false
    editor.editor.full_html:
      addItemToToolbar:
        item_name: aickeditor
        position: 0
      setProperties:
        settings.plugins.ai_ckeditor_ai:
          dialog:
            autoresize: 'min-width: 600px'
            height: '750'
            width: '900'
            dialog_class: ai-ckeditor-modal
          plugins:
            ai_ckeditor_completion:
              enabled: true
              provider: ''
            ai_ckeditor_help:
              enabled: false
            ai_ckeditor_modify_prompt:
              enabled: false
              provider: ''
            ai_ckeditor_reformat_html:
              enabled: true
              provider: ''
            ai_ckeditor_spellfix:
              enabled: false
              provider: ''
            ai_ckeditor_summarize:
              enabled: true
              provider: ''
            ai_ckeditor_tone:
              enabled: false
              provider: ''
              autocreate: false
              tone_vocabulary: tags
              use_description: false
            ai_ckeditor_translate:
              enabled: false
              provider: ''
              language_source: lang
              autocreate: false
              translate_vocabulary: tags
              use_description: false
