#!/bin/bash

## Description: Export configuration  and commit it to local Git repository
## Usage: config-export
## Example: ddev config-export
## ProjectTypes: drupal,drupal11


echo "Creating a config snapshot via GIT"
if [ ! -d "config/sync" ]; then
  mkdir -p config/sync
  git -C config/sync init
fi
drush config:export -qy
git -C config/sync add .
git -C config/sync commit -m "Updating config snapshot"
