#!/bin/bash

## Description: Runs Eslint
## Usage: eslint [flags] [args]
## Example: ddev eslint\nddev eslint web/modules/sandbox/schemadotorg

# @see https://www.drupal.org/node/2873849

source .commands.sh

# Copy .prettierrc.json and .prettierignore.
if [ -d "$PARAMETERS" ]; then
  cp $DDEV_DOCROOT/core/.prettierrc.json $PARAMETERS/.prettierrc.json
  echo '*.yml' > $PARAMETERS/.prettierignore
fi

# Run eslint.
$DDEV_DOCROOT/core/node_modules/.bin/eslint --no-error-on-unmatched-pattern --resolve-plugins-relative-to=$DDEV_DOCROOT/core --ext=.js $OPTIONS $PARAMETERS

# Remove .prettierrc.json and .prettierignore.
if [ -d "$PARAMETERS" ]; then
  rm $PARAMETERS/.prettierrc.json
  rm $PARAMETERS/.prettierignore
fi
