#!/bin/bash

## Description: Runs PHPUnit
## Usage: phpunit [flags] [args]
## Example: ddev phpunit\nddev phpunit web/modules/custom

# @see https://www.drupal.org/docs/automated-testing/phpunit-in-drupal/running-phpunit-tests

source "$HOME/.commands.sh"

./vendor/bin/phpunit $OPTIONS $PARAMETERS
